default_agent: safety_signal
agents:
  safety_signal:
    name: safety_signal
    entrypoint: /Users/jrgaines/github/amazon-bedrock-agents-healthcare-lifesciences/agents_catalog/22-Safety-Signal-Detection-Agent/agentcore/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '864228002124'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: safety_signal-cK5qF36O8B
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:864228002124:runtime/safety_signal-cK5qF36O8B
      agent_session_id: c38d8bff-4a24-40c7-96d0-969ae4586133
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
