#!/usr/bin/env python3
"""Convert Biomni schema .pkl files to .json format.

Usage:
    python convert_pkl_to_json.py /path/to/schema_db/

This script converts all .pkl files in the schema_db directory to .json format.
The .pkl files are generated by the Biomni project (https://github.com/snap-stanford/Biomni).
After conversion, the .pkl files can be removed and the Lambda will use .json instead.
"""

import json
import os
import pickle  # nosec B403 - only used in this one-time conversion script
import sys


def convert_pkl_to_json(schema_dir: str) -> None:
    """Convert all .pkl files in schema_dir to .json files."""
    if not os.path.isdir(schema_dir):
        print(f"Error: {schema_dir} is not a directory")
        sys.exit(1)

    pkl_files = [f for f in os.listdir(schema_dir) if f.endswith(".pkl")]
    if not pkl_files:
        print(f"No .pkl files found in {schema_dir}")
        sys.exit(0)

    print(f"Converting {len(pkl_files)} .pkl files to .json...")

    for pkl_file in sorted(pkl_files):
        pkl_path = os.path.join(schema_dir, pkl_file)
        json_file = pkl_file.replace(".pkl", ".json")
        json_path = os.path.join(schema_dir, json_file)

        with open(pkl_path, "rb") as f:
            data = pickle.load(f)  # nosec B301 - one-time conversion of trusted files

        with open(json_path, "w") as f:
            json.dump(data, f, indent=2, default=str)

        print(f"  ✓ {pkl_file} → {json_file}")

    print(f"\nDone. {len(pkl_files)} files converted.")
    print("You can now remove the .pkl files:")
    print(f"  rm {schema_dir}/*.pkl")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} /path/to/schema_db/")
        sys.exit(1)
    convert_pkl_to_json(sys.argv[1])
